apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svelte
  template:
    metadata:
      labels:
        app: svelte
    spec:
      containers:
        - name: svelte
          image: 734793106345.dkr.ecr.ap-northeast-2.amazonaws.com/svel:2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svelte
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: svelte
